// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj_l2hHXFE9wMMzKcZg66iGtAN-KbQ1B8',
    appId: '1:625175170053:web:0229ed091588bb688fe06c',
    messagingSenderId: '625175170053',
    projectId: 'balance-8dcfa',
    authDomain: 'balance-8dcfa.firebaseapp.com',
    storageBucket: 'balance-8dcfa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj_l2hHXFE9wMMzKcZg66iGtAN-KbQ1B8',
    appId: '1:625175170053:android:0229ed091588bb688fe06c',
    messagingSenderId: '625175170053',
    projectId: 'balance-8dcfa',
    storageBucket: 'balance-8dcfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj_l2hHXFE9wMMzKcZg66iGtAN-KbQ1B8',
    appId: '1:625175170053:ios:0229ed091588bb688fe06c',
    messagingSenderId: '625175170053',
    projectId: 'balance-8dcfa',
    storageBucket: 'balance-8dcfa.firebasestorage.app',
    iosBundleId: 'com.example.yourApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj_l2hHXFE9wMMzKcZg66iGtAN-KbQ1B8',
    appId: '1:625175170053:macos:0229ed091588bb688fe06c',
    messagingSenderId: '625175170053',
    projectId: 'balance-8dcfa',
    storageBucket: 'balance-8dcfa.firebasestorage.app',
    iosBundleId: 'com.example.yourApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj_l2hHXFE9wMMzKcZg66iGtAN-KbQ1B8',
    appId: '1:625175170053:windows:0229ed091588bb688fe06c',
    messagingSenderId: '625175170053',
    projectId: 'balance-8dcfa',
    authDomain: 'balance-8dcfa.firebaseapp.com',
    storageBucket: 'balance-8dcfa.firebasestorage.app',
  );
}
